# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.CharField(max_length=255)),
                ('liveagent_id', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('affinity_token', models.CharField(max_length=255)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('ack', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'line_session',
            },
        ),
    ]
